import {
  Beef,
  CakeSlice,
  Coffee,
  CookingPot,
  Croissant,
  CupSoda,
  Egg,
  GlassWater,
  HandPlatter,
  Leaf,
  Milk,
  Pizza,
  Salad,
  Smile,
  Soup,
  Sun,
  UtensilsCrossed,
  Wheat,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon | undefined> = {
  breakfast: Sun,
  "starters-sides": Salad,
  "soups-hot-dishes": Soup,
  "grills-mains": Beef,
  bakery: Croissant,
  desserts: CakeSlice,
  "hot-drinks": Coffee,
  "cold-drinks": CupSoda,
  "ayran-yogurt": Milk,
  "breakfast-selections": HandPlatter,
  eggs: Egg,
  "breakfast-essentials": UtensilsCrossed,
  potatoes: CookingPot,
  starters: Salad,
  soups: Soup,
  "pasta-pizza": Pizza,
  grills: Beef,
  kids: Smile,
  "gozleme-borek": Croissant,
  pide: Wheat,
  coffee: Coffee,
  tea: Coffee,
  "mr-silver": GlassWater,
  "cold-coffee": Coffee,
  "signature-drinks": GlassWater,
  "fresh-juices": Leaf,
  "iced-tea-lemonade": CupSoda,
  "soft-drinks": CupSoda,
  milkshakes: Milk,
  ayran: Milk,
};

export function PresentationMenuIcon({ id }: { id: string }) {
  const Icon = ICONS[id];
  return Icon ? <Icon aria-hidden="true" /> : null;
}
